# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robin Beechey
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robinbeechey.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
angel_list: "https://angel.co/robin-beechey"
linkedin: "https://ca.linkedin.com/in/robinbeechey"
medium: "https://medium.com/@robinbeechey"
instagrams: "https://instagram.com/robinbeechey/"
mediaBucket: "http://media.robinbeechey.com/"

# Build settings

# Conversion
markdown: kramdown

# Handling Reading
include:
  - _pages
  - _projects



collections:
  - projects

